import random as rm
import turtle as trt
import math as m


def toit_circulaire(largeur_bat):
    pos = trt.position()
    trt.color(0, 0, 0)
    trt.goto(pos[0]+largeur_bat, pos[1])
    trt.pd()
    trt.begin_fill()
    trt.lt(90)
    trt.circle(largeur_bat//2,180)
    trt.lt(90)
    trt.end_fill()
    trt.pu()

def toit_triangulaire(largeur_bat):
    trt.color(0, 0, 0)
    pos_old = trt.position()
    hauteur_toit = max(rm.gauss(0.6, 0.3), 0.1) * largeur_bat
    trt.pd()
    trt.begin_fill()
    trt.goto(pos_old[0]+largeur_bat, pos_old[1])
    trt.goto(pos_old[0]+(largeur_bat//2), pos_old[1]+hauteur_toit)
    trt.goto(pos_old[0], pos_old[1])
    trt.end_fill()
    trt.pu()

def toit_plat(largeur_bat):
    trt.color(0, 0, 0)
    taille = trt.pensize()
    trt.pensize(10)
    pos = trt.position()
    trt.pd()
    trt.goto(pos[0]+largeur_bat, pos[1])
    trt.pu()
    trt.pensize(taille)

def etage(couleur, largeur, hauteur):
    oldcolor = trt.color()
    trt.color(couleur)
    trt.pd()
    trt.begin_fill()
    for i in range(2):
        trt.fd(largeur);trt.lt(90)
        trt.fd(hauteur);trt.lt(90)
    trt.end_fill()
    trt.pu()
    trt.color(oldcolor[0])

def fenetre_carre(largeur_bat:int,couleur:str,balcon:bool):
    trt.seth(0)
    "Dessine une fenêtre carrée en partant du coin inférieur gauche."
    trt.pensize(4)
    trt.color(couleur, "#88ffff")
    cote = largeur_bat//4
    old_pos = trt.pos()
    trt.pd()
    trt.begin_fill()
    trt.goto(old_pos[0],old_pos[1]+cote)
    trt.goto(old_pos[0]+cote,old_pos[1]+cote)
    trt.goto(old_pos[0]+cote,old_pos[1])
    trt.goto(old_pos)
    trt.pu()
    trt.end_fill()
    trt.pensize(3)
    trt.goto(old_pos[0],old_pos[1]+cote/2)
    trt.goto(old_pos[0]+cote,old_pos[1]+cote/2)
    trt.pu()
    trt.goto(old_pos[0]+cote/2,old_pos[1])
    trt.pd()
    trt.goto(old_pos[0]+cote/2,old_pos[1]+cote)
    trt.pu()

    if balcon == True :
        trt.pu()
        trt.pensize(2)
        trt.color('#777777')
        trt.goto(old_pos[0]-cote//6,old_pos[1]-cote//6)
        trt.pd()
        trt.lt(90)
        for i in range(int(cote//6)):
            trt.fd(cote//3)
            trt.rt(90)
            trt.fd(cote//8)
            trt.rt(90)
            trt.fd(cote//3)
            trt.lt(90)
            trt.fd(cote//8)
            trt.lt(90)
        trt.fd(cote//3)
        end_pos = trt.pos()
        trt.goto(old_pos[0]-cote//6,old_pos[1]+cote//6)
        trt.goto(old_pos[0]-cote//6,old_pos[1]-cote//6)
        trt.goto(end_pos[0],end_pos[1]-cote//3)
    trt.pu()
    if balcon == True :
        trt.goto(old_pos)
    trt.seth(0)
        
def fenetre_ronde(largeur_bat:int,couleur:str):
    "Dessine une fenêtre ronde en partant du coin inférieur droit."
    trt.pensize(5)
    trt.pu()
    trt.color(couleur, "#88ffff")
    rayon = largeur_bat/8
    old_pos = trt.pos()
    trt.goto(old_pos[0]+rayon,old_pos[1])
    trt.pd()
    trt.begin_fill()
    trt.circle(rayon)
    trt.pensize(3)
    trt.goto(old_pos[0]+rayon,old_pos[1]+2*rayon)
    trt.end_fill()
    trt.pu()
    trt.goto(old_pos[0],old_pos[1]+rayon)
    trt.pd()
    trt.begin_fill()
    trt.goto(old_pos[0]+2*rayon,old_pos[1]+rayon)
    trt.end_fill()
    trt.pu()
    trt.seth(0)

def porte_carree(largeur_bat:int, hauteur_étage:int,couleur:str):
    trt.pensize(5)
    trt.color(couleur)
    old_pos = trt.pos()
    trt.begin_fill()
    trt.pd()
    trt.goto(old_pos[0],old_pos[1]+hauteur_étage*3/5)    
    trt.goto(old_pos[0]+largeur_bat/4,old_pos[1]+hauteur_étage*3/5)
    trt.goto(old_pos[0]+largeur_bat/4,old_pos[1])
    trt.goto(old_pos)
    trt.end_fill()
    trt.pu()
    trt.seth(0)

def porte_ronde(largeur_bat:int, hauteur_étage:int,couleur:str):
    trt.pensize(4)
    trt.color(couleur)
    old_pos = trt.pos()
    trt.pd()
    trt.begin_fill()
    trt.goto(old_pos[0]+largeur_bat/4,old_pos[1])
    trt.goto(old_pos[0]+largeur_bat/4,old_pos[1]+hauteur_étage*3/5)
    trt.left(90)
    trt.circle(largeur_bat/8,180)
    trt.goto(old_pos)
    trt.end_fill()
    trt.pu()
    trt.goto(old_pos[0]+largeur_bat/8,old_pos[1]+hauteur_étage*3/10)
    trt.pensize(3)
    trt.seth(0)

def main():
    trt.setup(800, 800)
    trt.update()
    trt.pu()
    trt.speed(0)
    trt.hideturtle()
    trt.goto(-400, -301)
    trt.color("#000000")
    trt.pd()
    trt.begin_fill()
    trt.goto(400, -301)
    trt.goto(400, -400)
    trt.goto(-400, -400)
    trt.goto(-400, -301)
    trt.end_fill()
    trt.pu()
